<?php

namespace Project\CarRentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarsDataBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsDataBaseRepository extends EntityRepository
{
}
