login:
    path:   /
    defaults:  { _controller: FOSUserBundle:Security:login }

orders:
    path:   /homepage/orders
    defaults:  { _controller: ProjectCarRentBundle:Orders:orders }

project_car_rent_homepage:
    path:     /homepage
    defaults: { _controller: ProjectCarRentBundle:Default:index }

project_car_rent_menu:
    path:     /homepage/{menu}
    defaults: { _controller: ProjectCarRentBundle:Default:menu }

project_car_rent_car:
    path:     /homepage/car/{car}
    defaults: { _controller: ProjectCarRentBundle:Default:car }

